CREATE TRIGGER CHECK_FORM_1
    ON MAINTENANCE_RECORDS
    AFTER INSERT
AS
BEGIN

	DECLARE @C INT;
SELECT @C = COUNT(*) FROM MAINTENANCE_RECORDS WHERE DateReceived = (SELECT DateReceived FROM inserted);
IF(@C = 31)
BEGIN
ROLLBACK TRANSACTION
END
END